version: 1.0.0-alpha{build}
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
init:
- ps: $env:customnugetversion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_REPO_TAG_NAME" } else { "$env:APPVEYOR_BUILD_VERSION" }
- ps: Update-AppveyorBuild -Version $env:customnugetversion
dotnet_csproj:
  patch: true
  file: src\**\*.csproj
  package_version: '{version}'
  informational_version: '{version}'
environment:
  nuget-api-key:
    secure: cdk1PHxgO0eToAllOUT1sqZdSDsjcOTTR2tNX9ro5+WwnFVIhPv/hUifBEzs4A2Q
nuget:
  account_feed: true
build_script:
- cmd: dotnet build -c release
test_script:
- cmd: dotnet test
deploy:
- provider: NuGet
  api_key:
    secure: cdk1PHxgO0eToAllOUT1sqZdSDsjcOTTR2tNX9ro5+WwnFVIhPv/hUifBEzs4A2Q
  skip_symbols: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://ci.appveyor.com/nuget/sanisoclem-1hsskq6nn06g
  api_key:
    secure: ovRAAP+pCt2eBZ5OoCKJaGh4vQbTUAZ8wnbsogY3sYw=
  skip_symbols: true
  on:
    branch: master